# Generated by Django 3.2.1 on 2021-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='mob',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='register',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
