# Generated by Django 3.2.1 on 2021-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210506_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='user_img',
            field=models.ImageField(default='', upload_to='user_img/dp'),
        ),
    ]
