# Generated by Django 3.2.1 on 2021-06-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='user_img',
        ),
    ]
