# Generated by Django 3.2.1 on 2021-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_alter_register_mob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_img', models.ImageField(default='', upload_to='user_img/dp/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
