# Generated by Django 3.2.1 on 2021-07-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='user_img',
            field=models.FileField(default='', upload_to='user_img/dp/'),
        ),
    ]
