# Generated by Django 3.2.1 on 2021-07-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_alter_home_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='user_img',
            field=models.ImageField(default='', upload_to='user_img/dp/%d'),
        ),
    ]
